version: 3

services:
  frontend:
    build:
      context: ./frontend
    ports: 
      -"9000:9000"
    depends_on:
      - backend
    
  backend:
  build:
    context: ./backend
  ports:
    -"5000:5000"
